// DistinctSubstrings
// Distinct Substrings
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac DistinctSubstrings.java
// Run:
//   java DistinctSubstrings
//
// Author: Generated by assistant

public class DistinctSubstrings {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for DistinctSubstrings - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
