// HuffmanCoding
// Huffman Coding
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac HuffmanCoding.java
// Run:
//   java HuffmanCoding
//
// Author: Generated by assistant

public class HuffmanCoding {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for HuffmanCoding - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
