// CountWordsInTrie
// Count Words in Trie
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac CountWordsInTrie.java
// Run:
//   java CountWordsInTrie
//
// Author: Generated by assistant

public class CountWordsInTrie {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for CountWordsInTrie - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
