// TrieOperations
// Trie — Insert Search Delete
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac TrieOperations.java
// Run:
//   java TrieOperations
//
// Author: Generated by assistant

public class TrieOperations {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for TrieOperations - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
