// BasicHashFunction
// Basic Hash Function
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac BasicHashFunction.java
// Run:
//   java BasicHashFunction
//
// Author: Generated by assistant

public class BasicHashFunction {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for BasicHashFunction - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
