// TwoSumHashMap
// Two Sum Using HashMap
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac TwoSumHashMap.java
// Run:
//   java TwoSumHashMap
//
// Author: Generated by assistant

public class TwoSumHashMap {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for TwoSumHashMap - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
