// BuildBST
// Build a BST
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac BuildBST.java
// Run:
//   java BuildBST
//
// Author: Generated by assistant

public class BuildBST {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for BuildBST - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
