// ValidateBST
// Validate a BST (isValidBST)
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac ValidateBST.java
// Run:
//   java ValidateBST
//
// Author: Generated by assistant

public class ValidateBST {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for ValidateBST - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
