// BoundaryTraversal
// Boundary Traversal of Binary Tree
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac BoundaryTraversal.java
// Run:
//   java BoundaryTraversal
//
// Author: Generated by assistant

public class BoundaryTraversal {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for BoundaryTraversal - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
