// LeftViewBinaryTree
// Left View of Binary Tree
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac LeftViewBinaryTree.java
// Run:
//   java LeftViewBinaryTree
//
// Author: Generated by assistant

public class LeftViewBinaryTree {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for LeftViewBinaryTree - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
