// MaxDepthBinaryTree
// Max Depth of Binary Tree
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac MaxDepthBinaryTree.java
// Run:
//   java MaxDepthBinaryTree
//
// Author: Generated by assistant

public class MaxDepthBinaryTree {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for MaxDepthBinaryTree - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
