// TreeTraversals
// Tree Traversals
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac TreeTraversals.java
// Run:
//   java TreeTraversals
//
// Author: Generated by assistant

public class TreeTraversals {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for TreeTraversals - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
