// ProductOfThreeLargest
// Product of Three Largest Distinct Elements
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac ProductOfThreeLargest.java
// Run:
//   java ProductOfThreeLargest
//
// Author: Generated by assistant

import java.util.*;


public class ProductThreeLargest {


public static int product(int[] arr) {
    
// Step 1: Remove duplicates using HashSet
Set<Integer> set = new HashSet<>();
for (int x : arr) set.add(x);


// Step 2: Max Heap using PriorityQueue
PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());
pq.addAll(set);


// Step 3: Check if at least 3 distinct elements exist
if (pq.size() < 3) return -1;


int a = pq.poll();
int b = pq.poll();
int c = pq.poll();


return a * b * c;
}


public static void main(String[] args) {
int[] arr = {10, 3, 5, 6, 20, 20};
System.out.println("Product: " + product(arr));
}
}
